# WARNING - Generated by {fusen} from dev/flat_utils-functions.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("FactorFromFileName works", {
  
  # 1. We start with a character vector of file names
  files <- c("2023_Albumin_01.csv", "2023_Hemoglobin_02.csv", "2023_Insulin_03.csv")
  
  # 2. We want to split by "_" and extract the second element (between the underscores)
  #    We also want to add a prefix "ID_" to the extracted factor
  names <- FactorFromFileName(
    x         = files, 
    separator = "_", 
    position  = 2, 
    prefix    = "ID_", 
    suffix    = ""  )

    expect_equal(names, c("ID_Albumin", "ID_Hemoglobin", "ID_Insulin"))

})
