# WARNING - Generated by {fusen} from dev/flat_graphics-functions.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("renderDistributionPlot works", {
  
  data(iris)
  
  p <- renderDistributionPlot(
    df    = iris,
    x_var = "Species",
    y_var = "Sepal.Length",
    type  = "violin"
  )
  
  expect_s3_class(p, "ggplot")
  expect_false(is.null(p$data))
  expect_no_error(p)
  expect_true(length(p$layers) > 0)

})

test_that("run_pca works", {
  
  data(iris)
  iris_num <- iris[, 1:4]

  res <- run_pca(
    numerics    = iris_num,
    active_cols = c("Sepal.Length", "Sepal.Width")
  )

  expect_s3_class(res, "PCA")
  expect_true(!is.null(res$eig))
  expect_true(ncol(res$ind$coord) <= 2)
    
  #---------------------------------------------------
  
  res <- run_pca(
    numerics    = iris_num,
    active_cols = c("Sepal.Length", "Sepal.Width"),
    supp_vars   = c("Petal.Length", "Petal.Width")
  )

  expect_s3_class(res, "PCA")
  expect_true(!is.null(res$quanti.sup))
  
  #---------------------------------------------------

  train <- iris_num[1:100, ]
  supp  <- iris_num[101:110, ]

  res <- run_pca(
    numerics    = train,
    active_cols = c("Sepal.Length", "Sepal.Width"),
    supp_inds   = supp
  )

  expect_s3_class(res, "PCA")
  expect_true(!is.null(res$ind.sup))
  
  #---------------------------------------------------

  train <- iris_num[1:100, ]
  supp  <- iris_num[101:110, ]

  res <- run_pca(
    numerics    = train,
    active_cols = c("Sepal.Length", "Sepal.Width"),
    supp_vars   = c("Petal.Length", "Petal.Width"),
    supp_inds   = supp
  )

  expect_s3_class(res, "PCA")
  expect_true(!is.null(res$quanti.sup))
  expect_true(!is.null(res$ind.sup))
  
})

test_that("plot_screeplot works", {

  data(iris)

  res_pca <- FactoMineR::PCA(iris[, 1:4], graph = FALSE)

  p <- plot_screeplot(res_pca)

  expect_s3_class(p, "ggplot")
  
  #---------------------------------------------------------------------

  res_pca <- FactoMineR::PCA(iris[, 1:2], graph = FALSE)

  p <- plot_screeplot(res_pca)

  expect_s3_class(p, "ggplot")

  #---------------------------------------------------------------------

  res_pca <- FactoMineR::PCA(iris[, 1:4], graph = FALSE)

  p <- plot_screeplot(res_pca)

  max_eig <- max(res_pca$eig[, 2])

  # Extract y range from ggplot object
  y_range <- ggplot2::ggplot_build(p)$layout$panel_scales_y[[1]]$range$range

  expect_equal(max(y_range), max_eig)

 })

test_that("plot_corcircle works", {
  
  data(decathlon2, package = "factoextra")
  
  res.pca <- FactoMineR::PCA(
    decathlon2[1:23, 1:10],
    graph = FALSE
  )
  
  p <- plot_corcircle(res.pca, 1, 2)
  
  expect_s3_class(p, "ggplot")
  expect_no_error(p)
  expect_true(length(p$layers) > 0)
  
  #-------------------------------
  
  res.pca <- FactoMineR::PCA(
    decathlon2[1:23, 1:12],
    quanti.sup = 11:12,
    graph = FALSE
  )
  
  p <- plot_corcircle(res.pca, 3, 4)
  
  expect_s3_class(p, "ggplot")
  
  
})


test_that("plot_bivariate handles iris-based PCA and verifies labels", {
  
  # 1. Setup data with iris
  # Using first 140 as active, last 10 as supplementary
  data_active <- iris[1:140, 1:4]
  data_sup    <- iris[141:150, 1:4]
  full_data   <- rbind(data_active, data_sup)
  
  # Run PCA
  res_pca <- FactoMineR::PCA(full_data, ind.sup = 141:150, graph = FALSE)
  
  # Prepare factors
  fac_df <- data.frame(
    Species   = iris$Species,
    row.names = rownames(iris)
  )
  
  # 2. Execute function
  p <- plot_bivariate(res_pca, fac_df, "Species")
  
  # --- Assertions ---
  
  # Verify object type
  expect_s3_class(p, "ggplot")
  
  # To avoid the NULL issue with labels, we can check the labs list directly 
  # or verify the scale aesthetics
  expect_equal(p$labels$colour, "Species")
  
  # Check if "supp. ind." is present in the plot data
  # Since we added it to ind_sup$group, we check the layers
  has_supp_layer <- any(sapply(p$layers, function(l) {
    if(!is.null(l$data)) return("supp. ind." %in% l$data$group)
    return(FALSE)
  }))
  expect_true(has_supp_layer)
  
  # Verify variance percentage is present in X label
  # Dim 1 for iris is approx 73.0%
  expected_pct <- paste0(round(res_pca$eig[1, 2], 1), "%")
  expect_match(p$labels$x, expected_pct)
  
  # Check for error when column is missing
  expect_error(
    plot_bivariate(res_pca, fac_df, "Unknown"),
    "factor_col must be a column name of factors"
  )
})

