# WARNING - Generated by {fusen} from dev/flat_analyses-functions.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("polynom.sur works", {
    
  tmp <- tempdir()
  
  sur <- system.file("tests/sur/test_surf.sur", package = "trident")
  
  out <- file.path(tmp, "test_surf.sur")
  
  file.copy(from = sur, to = out)

  sur <- out
  out <- file.path(tmp, "test_surf_X1_001_Y1_001.sur")

  if (file.exists(out)) file.remove(out)
  
  ResPol <- polynom.sur(sur = sur, TmpDir = tmp, deg = 1, path = TRUE)
  
  expect_true(file.exists(out))
  
})

test_that("dmta.height works", {
    
  tmp <- tempdir()
  sur <- system.file("tests/sur/test_surf.sur", package = "trident")

  ResHgt <- dmta.height(sur = sur, TmpDir = tmp, size.x = 256,
                                                 size.y = 256, size.n = 256, type = "single")
  
  expect_type(ResHgt, "list")
  
  expect_named(ResHgt, c("File", "Type", "Sa", "Sp", "Sq", "Sv", "Ssk", "Sku", "Sdar", "Sm", "Smd"))
  
  expect_equal(ResHgt$File, basename(sur))
  expect_equal(ResHgt$Type, "height")
  expect_type(ResHgt$Sa,    "double")
  expect_type(ResHgt$Sp,    "double")
  expect_type(ResHgt$Sq,    "double")
  expect_type(ResHgt$Sv,    "double")
  expect_type(ResHgt$Ssk,   "double")
  expect_type(ResHgt$Sku,   "double") 
  expect_type(ResHgt$Sdar,  "double")
  expect_type(ResHgt$Sm,    "double")
  expect_type(ResHgt$Smd,   "double")
  
  ResHgtMulti <- dmta.height(sur = sur, TmpDir = tmp, size.x = 256,
                                                      size.y = 256, size.n = 256, type = "multi")
  
  expect_type(ResHgtMulti, "list")
  
  expect_named(ResHgtMulti, c("File", "Type", "Sa", "Sp", "Sq", "Sv", "Ssk", "Sku",
                                              "Sdar", "Sm", "Smd"))
  
  expect_equal(ResHgtMulti$File, basename(sur))
  expect_equal(ResHgtMulti$Type, "height")

  numeric_fields  <- c("Sa","Sp","Sq","Sv","Ssk","Sku","Sdar","Sm","Smd")
  
  expected_length <- 256
  
  for(i in seq_along(numeric_fields)) {
      
    field <- numeric_fields[i]
    
    expect_type  (ResHgtMulti[[field]], "double")
    expect_length(ResHgtMulti[[field]], expected_length)
    
  }
  
})

test_that("dmta.spatial works", {
    
  tmp <- tempdir()
  sur <- system.file("tests/sur/test_surf.sur", package = "trident")

  ResSpt <- dmta.spatial(sur = sur, TmpDir = tmp, size.x = 256, size.y = 256, size.n = 256, type = "single")
  
  expect_type(ResSpt, "list")
  
  expect_named(ResSpt, c("File", "Type", "Rmax", "Sal", "Stri", "Std", "b.sl", "r.sl", "s.sl"))
  
  expect_equal(ResSpt$File, basename(sur))
  expect_equal(ResSpt$Type, "spatial")
  expect_type (ResSpt$Rmax, "double")
  expect_type (ResSpt$Sal,  "double")
  expect_type (ResSpt$Stri, "double")
  expect_type (ResSpt$Std,  "double")
  expect_type (ResSpt$b.sl, "double")
  expect_type (ResSpt$r.sl, "double") 
  expect_type (ResSpt$s.sl, "double")

  ResSptMulti <- dmta.spatial(sur = sur, TmpDir = tmp, size.x = 256, size.y = 256, size.n = 256, type = "multi")
  
  expect_type(ResSptMulti, "list")
  
  expect_named(ResSptMulti, c("File", "Type", "Rmax", "Sal", "Stri", "Std", "b.sl", "r.sl", "s.sl"))
  
  expect_equal(ResSptMulti$File, basename(sur))
  expect_equal(ResSptMulti$Type, "spatial")

  numeric_fields  <- c("Rmax", "Sal", "Stri", "Std", "b.sl", "r.sl", "s.sl")
  
  expected_length <- 256
  
  for(i in seq_along(numeric_fields)) {
      
    field <- numeric_fields[i]
    
    expect_type  (ResSptMulti[[field]], "double")
    expect_length(ResSptMulti[[field]], expected_length)
    
  }
  
})

test_that("dmta.topology works", {
    
  tmp <- tempdir()
  sur <- system.file("tests/sur/test_surf2.sur", package = "trident")

  ResTop <- dmta.topology(sur = sur, TmpDir = tmp, size.x = 256, size.y = 256, size.n = 256, type = "single")
  
  expect_type(ResTop, "list")
  
  expect_named(ResTop, c("File", "Type", "Sk1", "Sk2", "Smc1", "Smc2", "Snb1", "Snb2", "Sh"))
  
  expect_equal(ResTop$File, basename(sur))
  expect_equal(ResTop$Type, "topology")
  expect_type(ResTop$Sk1,   "double")
  expect_type(ResTop$Sk2,   "double")
  expect_type(ResTop$Smc1,  "double")
  expect_type(ResTop$Smc2,  "double")
  expect_type(ResTop$Snb1,  "double")
  expect_type(ResTop$Snb2,  "double") 
  expect_type(ResTop$Sh,    "double")

  ResTopMulti <- dmta.topology(sur = sur, TmpDir = tmp, size.x = 256, size.y = 256, size.n = 256, type = "multi")
  
  expect_type(ResTopMulti, "list")
  
  expect_named(ResTopMulti, c("File", "Type", "Sk1", "Sk2", "Smc1", "Smc2", "Snb1", "Snb2", "Sh"))
  
  expect_equal(ResTopMulti$File, basename(sur))
  expect_equal(ResTopMulti$Type, "topology")

  numeric_fields  <- c("Sk1", "Sk2", "Smc1", "Smc2", "Snb1", "Snb2", "Sh")
  
  expected_length <- 256
  
  for(i in seq_along(numeric_fields)) {
      
    field <- numeric_fields[i]
    
    expect_type  (ResTopMulti[[field]], "double")
    expect_length(ResTopMulti[[field]], expected_length)
    
  }
  
})

test_that("dmta.asfc works", {
    
  tmp <- tempdir()
  sur <- system.file("tests/sur/test_surf2.sur", package = "trident")

  ResAsf <- dmta.asfc(sur = sur, TmpDir = tmp, size.x = 256,
                                               size.y = 256, size.n = 256, type = "single")
  
  expect_type(ResAsf, "list")
  
  expect_named(ResAsf, c("File", "Type", "Asfc2", "R2adj"))
  
  expect_equal(ResAsf$File, basename(sur))
  expect_equal(ResAsf$Type, "complexity")
  expect_type(ResAsf$Asfc2, "double")
  expect_type(ResAsf$R2adj, "double")

  ResAsfMulti <- dmta.asfc(sur = sur, TmpDir = tmp, size.x = 256,
                                                    size.y = 256, size.n = 256, type = "multi")
  
  expect_type(ResAsfMulti, "list")
  
  expect_named(ResAsfMulti, c("File", "Type", "Asfc2", "R2adj"))
  
  expect_equal(ResAsfMulti$File, basename(sur))
  expect_equal(ResAsfMulti$Type, "complexity")

  numeric_fields  <- c("Asfc2", "R2adj")
  
  expected_length <- 256
  
  for(i in seq_along(numeric_fields)) {
      
    field <- numeric_fields[i]
    
    expect_type  (ResAsfMulti[[field]], "double")
    expect_length(ResAsfMulti[[field]], expected_length)
    
  }
  
})

test_that("trident.hetero works", {
   
  x <- c(
    12, 15, NA, 18, 21, -14, NA, 19, 23, 17,
    16, 20, NA, 22, 24,  13, 11, NA, 25, 26,
    27, 28, 29, NA, 30, -10,  9,  8,  7,  6
        ) 
  
  DFstat <- trident.hetero(x, var.name = "ExampleVariable")

    expected <- data.frame(
      min    = -14,
      max    = 30,
      sd     = 11.06014,
      mean   = 16.08,
    
      median = 18,
      fst.05 = -6.8,
      lst.05 = 28.8,
    
      min.05 = -12,
      max.05 = 29.5,
    
      fst.25 = 11,
      lst.25 = 24,
    
      min.25 = 2.428571,
      max.25 = 27,
    
      skw    = -1.09558,
      kurt   = 0.8237028
    )
  
  expect_equal(DFstat, expected, tolerance = 1e-6) # to allow for small numerical differences in the calculations of sd, skewness and kurtosis.

})


test_that("Batch.fun works", {
    
  sur <- system.file("tests/sur/test_surf2.sur", package = "trident")
  
  Mytable <- Batch.fun(sur = sur, size = 256, nCell = 64, peakRemoval = "0",
            doStd = TRUE,
            doComplexity = TRUE, doHeight = TRUE, doSpatial = TRUE, doTopology = TRUE,
            doHComplexity = TRUE, doHHeight = TRUE, doHSpatial = TRUE, doHTopology = TRUE)

  expect_type(Mytable, "list")
  
  vars <- c("Asfc2", "R2adj", "Sa", "Sp", "Sq", "Sv", "Ssk", "Sku", "Sdar", "Sm", "Smd",
            "Rmax", "Sal", "Stri", "Std", "b.sl", "r.sl", "s.sl",
            "Sk1", "Sk2", "Smc1", "Smc2", "Snb1", "Snb2", "Sh")
  
  stats <- c("min","max","sd","mean","median",
             "fst.05","lst.05","min.05","max.05",
             "fst.25","lst.25","min.25","max.25","skw","kurt")
  
  expected_columns <- c("File", vars, vars[-2] %>% purrr::map(~ paste0(.x, ".", stats))
                                                 %>% unlist()) # to generate the expected column names by combining variable names and statistic names with an underscore.
  
  expect_equal(colnames(Mytable), expected_columns)
  
})
