# WARNING - Generated by {fusen} from dev/flat_statistics-functions.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("statistics_functions works", {
  
  csv <- system.file("tests/csv/Vars.csv", package = "trident")
  
  df  <- read.csv(file = csv, header = TRUE, as.is = TRUE, row.names = NULL)

  fa <- as.factor(c(rep("A", 15), rep("B", 15), rep("C", 15)))

  df[] <- lapply(df, as.numeric)

  DFstat <- data.frame(multicheck(df = df, y = fa, alpha = 0.05))

  csv <- system.file("tests/csv/DFstat_ref.csv", package = "trident")

  expected <- read.csv(file = csv, header = TRUE, as.is = TRUE, row.names = NULL)
  
  crit <- c("anova_p.value", "bartlett_p.value", "kruskal_p.value", "levene_p.value", "shapiro_p.value", "variance.ratio")
  
  expect_equal(DFstat[crit], expected[crit], tolerance = 1e-6) # to allow for small numerical differences in the calculations

  #---
  
  crit <- c("is.normal", "is.homoscedastic", "is.discriminant")
  
  expected[crit] <- lapply(expected[crit], as.character)

  expect_equal(DFstat[crit], expected[crit]) # exact match for the decision flags

  #---

  crit <- c("skewness.ratio")
  
  expect_equal(DFstat[crit], expected[crit], tolerance = 0.2) # skewness ratio is more variable due to bootstrap, so we use a higher tolerance here 

})

test_that("boxcox_functions works", {
  
    csv <- system.file("tests/csv/Example_BoxCox.csv", package = "trident")
    
    df <- read.csv(file = csv, header = TRUE, as.is = TRUE, row.names = NULL)

    fact <- as.factor(c(rep("A", 15), rep("B", 15), rep("C", 15)))

    expected <- c(0.0, -0.8)
  
    df_lambda <- trident.boxcox(df = df, y = fact, list.lambda = TRUE)$lambda

    expect_equal(df_lambda, expected, tolerance = 0.01) # to allow for small numerical differences in the estimation of lambda

})

test_that("trident.top3 works", {

  df <- mtcars[, c("mpg","disp","hp","drat","wt","qsec")]
  y  <- factor(mtcars$cyl)

  # ---- Execution ----
  res <- trident.top3(df = df, y = y)

  # ---- Checks structure ----
  expect_true(is.list(res))
  expect_true(all(c("top3var", "ranked") %in% names(res)))

  expect_true(is.vector(res$top3var))
  expect_true(length(res$top3var) > 0)

  expect_true(is.data.frame(res$ranked))
  expect_true("group" %in% colnames(res$ranked))
  
})

test_that("run_posthoc works", {

  skip_if_not_installed("DescTools")

  res <- run_posthoc(
    x = iris$Sepal.Length,
    y = iris$Species,
    method = "hsd",
    alpha = 0.05
  )

  # 1. output is numeric
  expect_type(res, "double")

  # 2. last element is n_signif (integer-like)
  expect_true(length(res) >= 4)

  n_signif <- tail(res, 1)
  expect_true(n_signif >= 0)

  # 3. avg_p and geo_p are in valid range [0,1] or sentinel 1
  avg_p <- res[length(res) - 2]
  geo_p <- res[length(res) - 1]

  expect_true(avg_p == 1 || (avg_p >= 0 && avg_p <= 1))
  expect_true(geo_p == 1 || (geo_p >= 0 && geo_p <= 1))
})

test_that("trident.arrange works", {

  df <- iris[, 1:4]
  y  <- iris$Species

  res <- trident.arrange(df    = df,
                         y     = y,
                         by    = "f.stat",
                         alpha = 0.05
  )

  expect_true(is.data.frame(res))
  expect_equal(nrow(res), ncol(df))
  expect_true(all(rownames(res) %in% colnames(df)))

  expect_true("f.stat" %in% colnames(res))
  expect_true(any(grepl("aov.p.value", colnames(res))))
  
})

