# WARNING - Generated by {fusen} from dev/flat_analyses-functions.Rmd: do not edit by hand # nolint: line_length_linter.

#' @title Analyses functions
#' @description Internal grouping function
#' @noRd
analyses <- function() {
  NULL
}

# Batch.fun----
#' @title Batch.fun
#' @description
#' Runs a batch computation of DMTA (surface texture analysis) metrics
#' using the `trident` package. Computes complexity, height, spatial,
#' and topology parameters with optional heterogeneity measures.
#'
#' @param sur Character. Path to the `.sur` file.
#' @param size Numeric. Size of the analysis window (x and y resolution).
#' @param nCell Integer. Number of cells for multi-scale analysis.
#' @param peakRemoval Character or numeric. Controls polynomial surface
#' correction (e.g. "2", "8", or NULL).
#' @param doStd Logical. Whether to compute standardized spatial metrics.
#' @param doComplexity Logical. Compute complexity metrics (ASFC, R2adj).
#' @param doHeight Logical. Compute height parameters.
#' @param doSpatial Logical. Compute spatial parameters.
#' @param doTopology Logical. Compute topological parameters.
#' @param doHComplexity Logical. Compute heterogeneity for complexity.
#' @param doHHeight Logical. Compute heterogeneity for height.
#' @param doHSpatial Logical. Compute heterogeneity for spatial metrics.
#' @param doHTopology Logical. Compute heterogeneity for topology.
#'
#' @return A data.frame containing computed DMTA metrics for the input file.
#' @export
#' @examples
#'
#' sur <- system.file("tests/sur/test_surf2.sur", package = "trident")
#'
#' Mytable <- Batch.fun(sur = sur, size = 256, nCell = 64, peakRemoval = "0",
#'           doStd = TRUE,
#'           doComplexity = TRUE, doHeight = TRUE, doSpatial = TRUE, doTopology = TRUE,
#'           doHComplexity = TRUE, doHHeight = TRUE, doHSpatial = TRUE, doHTopology = TRUE)
#'
#' dplyr::glimpse(Mytable)
Batch.fun <- function(sur, size, nCell, peakRemoval,
                        doStd,
                        doComplexity, doHeight, doSpatial, doTopology,
                        doHComplexity, doHHeight, doHSpatial, doHTopology) {

    TmpDir <- file.path(tempdir(), paste0("worker_", Sys.getpid()))
    dir.create(TmpDir, showWarnings = FALSE)

    if (peakRemoval == "2") {
      trident::polynom.sur(sur, TmpDir = TmpDir, deg = 2)
      sur <- stringr::str_replace(sur, "\\.sur$", "_X1_002_Y1_002.sur")
    }
    if (peakRemoval == "8") {
      trident::polynom.sur(sur, TmpDir = TmpDir, deg = 8)
      sur <- stringr::str_replace(sur, "\\.sur$", "_X1_008_Y1_008.sur")
    }


    # Prepare data frame
    Mytable <- data.frame(File = basename(sur), stringsAsFactors = TRUE)

    # DMTA Computation:
    if (doComplexity) {
      Complexity    <- trident::dmta.asfc(sur = sur, TmpDir = TmpDir, type = "single",
                                          size.x = size, size.y = size)
      
      Mytable$Asfc2 <- Complexity[3]
      Mytable$R2adj <- Complexity[4]
    }
    
    if (doHeight) {
      Elev <- trident::dmta.height(sur = sur, TmpDir = TmpDir, type = "single",
                                   size.x = size, size.y = size)
      
      Mytable$Sa   <- Elev[3]
      Mytable$Sp   <- Elev[4]
      Mytable$Sq   <- Elev[5]
      Mytable$Sv   <- Elev[6]
      Mytable$Ssk  <- Elev[7]
      Mytable$Sku  <- Elev[8]
      Mytable$Sdar <- Elev[9]
      Mytable$Sm   <- Elev[10]
      Mytable$Smd  <- Elev[11]
    }
    
    if (doSpatial) {
      Spat <- trident::dmta.spatial(sur = sur, TmpDir = TmpDir, type = "single",
                                    size.x = size, size.y = size)
      
      Mytable$Rmax <- Spat[3]
      Mytable$Sal  <- Spat[4]
      Mytable$Stri <- Spat[5]
      if (doStd){
      Mytable$Std  <- Spat[6]}
      Mytable$b.sl <- Spat[7]
      Mytable$r.sl <- Spat[8]
      Mytable$s.sl <- Spat[9]
    }
    
    if (doTopology) {
      Topo <- trident::dmta.topology(sur = sur, TmpDir = TmpDir, type = "single",
                                     size.x = size, size.y = size)
      
      Mytable$Sk1  <- Topo[3]
      Mytable$Sk2  <- Topo[4]
      Mytable$Smc1 <- Topo[5]
      Mytable$Smc2 <- Topo[6]
      Mytable$Snb1 <- Topo[7]
      Mytable$Snb2 <- Topo[8]
      Mytable$Sh   <- Topo[9]
    }
    
    # Heterogeneity

    if (doHComplexity) {
      HComplexity <- trident::dmta.asfc(sur = sur, TmpDir = TmpDir, type = "multi",
                                        size.x = size, size.y = size, size.n = nCell)
      
      hTable  <- c(plyr::colwise(trident::trident.hetero)(data.frame(HComplexity[3])))

      Mytable <- data.frame(Mytable, hTable)
    }

    if (doHHeight) {
      HElev <- trident::dmta.height(sur = sur, TmpDir = TmpDir, type = "multi",
                                    size.x = size, size.y = size, size.n = nCell)
      
      hTable  <- c(plyr::colwise(trident::trident.hetero)(data.frame(HElev[3:11])))

      Mytable <- data.frame(Mytable, hTable)
    }

    if (doHSpatial) {
      HSpat <- trident::dmta.spatial(sur = sur, TmpDir = TmpDir, type = "multi",
                                     size.x = size, size.y = size, size.n = nCell)
      
      if ( doStd) {
        hTable <- c(plyr::colwise(trident::trident.hetero)(data.frame(HSpat[3:9]))) }
      if (!doStd) {
        hTable <- c(plyr::colwise(trident::trident.hetero)(data.frame(HSpat[c(3,4,5,7,8,9)]))) }

      Mytable <- data.frame(Mytable, hTable)
    }

    if (doHTopology) {
      HTopo <- trident::dmta.topology(sur = sur, TmpDir = TmpDir, type = "multi",
                                      size.x = size, size.y = size, size.n = nCell)
      
      hTable  <- c(plyr::colwise(trident::trident.hetero)(data.frame(HTopo[3:9])))

      Mytable <- data.frame(Mytable, hTable)
    }

    # Return dataset
    return(Mytable)
  }

# dmta.asfc----
#' @title dmta.asfc
#' @description Computes Asfc variable
#' @param sur surface file
#' @param TmpDir temporary folder
#' @param size.x total x length of the surface, in pixels
#' @param size.y total y length of the surface, in pixels
#' @param size.n in case type = "multi", the number of cells for the calculation of heterogeneity
#' @param type character vector indicating whether a single value should be calculated for the whole surface ("single"); or if multiple values should be calculated for each n cells ("multi")
#' @return A list containing the .sur file, the type (complexity), Asfc2 and R2adj
#' @examples
#' #to do
#' tmp <- tempdir()
#' sur <- system.file("tests/sur/test_surf2.sur", package = "trident")
#'
#' ResAsf <- dmta.asfc(sur = sur, TmpDir = tmp, size.x = 256, 
#'                                              size.y = 256, size.n = 256, type = "single")
#'
#' dplyr::glimpse(ResAsf)
#'
#' @export
dmta.asfc <- function(sur, TmpDir, size.x = 256, size.y = 256, size.n = 256, type = "single") {

  #1-Preparation: move files to tmp
    
  Tmp <- stringr::str_replace_all(TmpDir, "\\\\", "/")
  Sur <- stringr::str_replace_all(sur, "\\\\", "/")

  NameSur <- unlist(strsplit(utils::tail(unlist(strsplit(sur, "\\\\")), 1), ".sur"))

  PrgPath <- system.file("extdata", "structure", "prg", "prg.exe", package = "trident")
  if (PrgPath == "") {PrgPath = "inst/extdata/structure/prg/prg.exe"}
  
  file.copy(from = PrgPath, to = Tmp)

  if (file.exists(file.path(Tmp, 'results_complex.txt'))) {
    file.remove(file.path(Tmp, 'results_complex.txt'))
  }
  
  #2-Recoding
  
  switch(type,
    "single" = {
      Sample.size <- "-0001"
    },
    "multi"  = {
      Sample.size <- paste0("+", size.n)
         },
    stop("type must be 'single' or 'multi'")
  )
  
  #3-Build the scripts

  Myscript <- glue::glue("
VERBOSES
.false.
.false.
'{file.path(Tmp, 'deroulement.txt')}'
 +006
'{file.path(Tmp, 'sortie.txt')}'
DEBUT___
    NB_PROCS
    -1
    LECT_BAS
    '{Sur}'
    .false.
    .false.
    TAB_BOOT
        +{size.x}
        +{size.y}
        {Sample.size}
    STA_LOOP
        +0001 {Sample.size}
        ANALYSES
            'complexi'
            '{file.path(Tmp, 'results_complex.txt')}'
            .true.
            -50
    END_LOOP
FIN_____
")
  
  utils::write.table(Myscript, file = file.path(Tmp, "complex_analysis.f90"), quote = FALSE, row.names = FALSE, col.names = FALSE)

  #4-Run the script
  
  system2(command = file.path(Tmp, "prg.exe"), args = file.path(Tmp, "complex_analysis.f90"), stdout = TRUE)


  #5-Scan and return the results
  
  Scanned  <- scan(file = file.path(Tmp, "results_complex.txt"), what = "character()")

  Results  <- t(matrix(Scanned [-(1:which(stringr::str_detect(Scanned,  "\\.sur")))], nrow = 4))

  idx      <- which(stringr::str_detect(Scanned, "\\.sur"))[1] # to get the index of the line containing the .sur file name,
                                                               # which is the first line of the results file. This is used
                                                               # to extract the file name for the output list.
  Filename <- basename(Scanned[idx])
  
  Asfc <- list(file  = Filename,
               type  = "complexity",
               asfc2 = as.numeric(Results[, 1]),
               r2adj = as.numeric(Results[, 2]))
  
  names(Asfc) <- c("File", "Type", "Asfc2", "R2adj")
  
  return(Asfc)
  
}

# dmta.height----
#' @title dmta.height
#' @description Computes height variables
#' @param sur surface file
#' @param TmpDir temporary folder
#' @param size.x total x length of the surface, in pixels
#' @param size.y total y length of the surface, in pixels
#' @param size.n in case type = "multi", the number of cells for the calculation of heterogeneity
#' @param type character vector indicating whether a single value should be calculated for the whole surface ("single"); or if multiple values should be calculated for each n cells ("multi")
#' @return A list containing the .sur file, the type (height), Sa, Sp, Sq, Sv, Ssk, Sku, Sdar, Sm and Smd
#' @examples
#' #to do
#' tmp <- tempdir()
#' sur <- system.file("tests/sur/test_surf.sur", package = "trident")
#'
#' ResHgt <- dmta.height(sur = sur, TmpDir = tmp, size.x = 256,
#'                                                size.y = 256, size.n = 256, type = "single")
#'
#' dplyr::glimpse(ResHgt)
#'
#' ResHgtMulti <- dmta.height(sur = sur, TmpDir = tmp, size.x = 256,
#'                                                     size.y = 256, size.n = 256, type = "multi")
#'
#' dplyr::glimpse(ResHgtMulti)
#'
#' @export
dmta.height <- function(sur, TmpDir, size.x = 256, size.y = 256, size.n = 256, type = "single") {

  #1-Preparation: move files to tmp
    
  Tmp <- stringr::str_replace_all(TmpDir, "\\\\", "/")
  Sur <- stringr::str_replace_all(sur, "\\\\", "/")

  NameSur <- unlist(strsplit(utils::tail(unlist(strsplit(sur, "\\\\")), 1), ".sur"))

  PrgPath <- system.file("extdata", "structure", "prg", "prg.exe", package = "trident")
  if (PrgPath == "") {PrgPath = "inst/extdata/structure/prg/prg.exe"}
  
  file.copy(from = PrgPath, to = Tmp)

  if (file.exists(file.path(Tmp, 'results_height.txt'))) {
    file.remove(file.path(Tmp, 'results_height.txt'))
  }

  if (file.exists(file.path(Tmp, 'results_faces.txt'))) {
    file.remove(file.path(Tmp, 'results_faces.txt'))
  }
  
  #2-Recoding
  
  switch(type,
    "single" = {
      Sample.size <- "-0001"
    },
    "multi"  = {
      Sample.size <- paste0("+", size.n)
         },
    stop("type must be 'single' or 'multi'")
  )
  
  #3-Build the scripts

  Myscript <- glue::glue("
VERBOSES
.false.
.false.
'{file.path(Tmp, 'deroulement.txt')}'
 +006
'{file.path(Tmp, 'sortie.txt')}'
DEBUT___
    NB_PROCS
    -1
    LECT_BAS
    '{Sur}'
    .false.
    .false.
    TAB_BOOT
        +{size.x}
        +{size.y}
        {Sample.size}
    STA_LOOP
        +0001 {Sample.size}
        ANALYSES
            'statisti'
            '{file.path(Tmp, 'results_height.txt')}'
            .true.
            -50
    END_LOOP
    TAB_BOOT
        +{size.x}
        +{size.y}
        {Sample.size}
    STA_LOOP
        +0001 {Sample.size}
        ANALYSES
            'facettes'
            '{file.path(Tmp, 'results_faces.txt')}'
            .true.
            -50
    END_LOOP
FIN_____
")

  utils::write.table(Myscript, file = file.path(Tmp, "height_analysis.f90"), quote = FALSE, row.names = FALSE, col.names = FALSE)

  #4-Run the script
  
  system2(command = file.path(Tmp, "prg.exe"), args = file.path(Tmp, "height_analysis.f90"), stdout = TRUE)


  #5-Scan and return the results
  
  Scanned  <- scan(file = file.path(Tmp, "results_height.txt"), what = "character()")
  Scanned2 <- scan(file = file.path(Tmp, "results_faces.txt"),  what = "character()")
  
  Results  <- t(matrix(Scanned [-(1:which(stringr::str_detect(Scanned,  "\\.sur")))], nrow = 16))
  Results2 <- t(matrix(Scanned2[-(1:which(stringr::str_detect(Scanned2, "\\.sur")))], nrow =  4))
  
  idx      <- which(stringr::str_detect(Scanned, "\\.sur"))[1] # to get the index of the line containing the .sur file name,
                                                               # which is the first line of the results file. This is used
                                                               # to extract the file name for the output list.
  Filename <- basename(Scanned[idx])
  
  Height <- list(file = Filename,
                 type = "height",
                 Sa   = as.numeric(Results [, 4]),
                 Sp   = as.numeric(Results [, 2]),
                 Sq   = as.numeric(Results [, 6]),
                 Sv   = as.numeric(Results [, 1]),
                 Ssk  = as.numeric(Results [, 7]),
                 Sku  = as.numeric(Results [, 8]),
                 Sdar = as.numeric(Results2[, 2]),
                 Sm   = as.numeric(Results [, 5]),
                 Smd  = as.numeric(Results [, 3]))
  
  names(Height) <- c("File", "Type", "Sa", "Sp", "Sq", "Sv", "Ssk", "Sku", "Sdar", "Sm", "Smd")
  
  return(Height)
}

# dmta.spatial----
#' @title dmta.spatial
#' @description Computes spatial variables
#' @param sur surface file
#' @param TmpDir temporary folder
#' @param size.x total x length of the surface, in pixels
#' @param size.y total y length of the surface, in pixels
#' @param size.n in case type = "multi", the number of cells for the calculation of heterogeneity
#' @param type character vector indicating whether a single value should be calculated for the whole surface ("single"); or if multiple values should be calculated for each n cells ("multi")
#' @return A list containing the .sur file, the type (spatial), Rmax, Sal, Stri, Std, b.sl, r.sl and s.sl
#' @examples
#' #to do
#' tmp <- tempdir()
#' sur <- system.file("tests/sur/test_surf.sur", package = "trident")
#'
#' ResSpt <- dmta.spatial(sur = sur, TmpDir = tmp, size.x = 256,
#'                                                 size.y = 256, size.n = 256, type = "single")
#'
#' dplyr::glimpse(ResSpt)
#'
#' ResSptMulti <- dmta.spatial(sur = sur, TmpDir = tmp, size.x = 256,
#'                                                      size.y = 256, size.n = 256, type = "multi")
#'
#' dplyr::glimpse(ResSptMulti)
#'
#' @export
dmta.spatial <- function(sur, TmpDir, size.x = 256, size.y = 256, size.n = 256, type = "single") {

  #1-Preparation: move files to tmp
    
  Tmp <- stringr::str_replace_all(TmpDir, "\\\\", "/")
  Sur <- stringr::str_replace_all(sur, "\\\\", "/")

  NameSur <- unlist(strsplit(utils::tail(unlist(strsplit(sur, "\\\\")), 1), ".sur"))

  PrgPath <- system.file("extdata", "structure", "prg", "prg.exe", package = "trident")
  if (PrgPath == "") {PrgPath = "inst/extdata/structure/prg/prg.exe"}
  
  file.copy(from = PrgPath, to = Tmp)

  if (file.exists(file.path(Tmp, 'results_spatial.txt'))) {
    file.remove(file.path(Tmp, 'results_spatial.txt'))
  }
  
  #2-Recoding
  
  switch(type,
    "single" = {
      Sample.size <- "-0001"
    },
    "multi"  = {
      Sample.size <- paste0("+", size.n)
         },
    stop("type must be 'single' or 'multi'")
  )
  
  #3-Build the scripts

  Myscript <- glue::glue("
VERBOSES
.false.
.false.
'{file.path(Tmp, 'deroulement.txt')}'
 +006
'{file.path(Tmp, 'sortie.txt')}'
DEBUT___
    NB_PROCS
    -1
    LECT_BAS
    '{Sur}'
    .false.
    .false.
    TAB_BOOT
        +{size.x}
        +{size.y}
        {Sample.size}
    STA_LOOP
        +0001 {Sample.size}
        ANALYSES
            'elli_acv'
            '{file.path(Tmp, 'results_spatial.txt')}'
            .true.
            -50
    END_LOOP
FIN_____
")

  utils::write.table(Myscript, file = file.path(Tmp, "spatial_analysis.f90"), quote = FALSE, row.names = FALSE, col.names = FALSE)

  #4-Run the script
  
  system2(command = file.path(Tmp, "prg.exe"), args = file.path(Tmp, "spatial_analysis.f90"), stdout = TRUE)


  #5-Scan and return the results
  
  Scanned  <- scan(file = file.path(Tmp, "results_spatial.txt"), what = "character()")

  Results  <- t(matrix(Scanned [-(1:which(stringr::str_detect(Scanned,  "\\.sur")))], nrow = 16))
  # to remove the first lines of the results file, which contain the .sur file name and the column names.
  # The remaining lines are then reshaped into a matrix with 16 columns (one for each variable) and as many rows as there
  # are samples (1 if type = "single", or size.n if type = "multi").

  idx      <- which(stringr::str_detect(Scanned, "\\.sur"))[1] # to get the index of the line containing the .sur file name,
                                                               # which is the first line of the results file. This is used
                                                               # to extract the file name for the output list.
  Filename <- basename(Scanned[idx])

  Spatial <- list(file = Filename,
                  type = "spatial",
                  rmax = as.numeric(Results[, 1]),
                  sal  = as.numeric(Results[, 2]),
                  stri = as.numeric(Results[, 3]),
                  std  = as.numeric(Results[, 4]),
                  b.sl = as.numeric(Results[, 6]),
                  r.sl = as.numeric(Results[, 7]),
                  s.sl = as.numeric(Results[, 5]))

  names(Spatial) <- c("File", "Type", "Rmax", "Sal", "Stri", "Std", "b.sl", "r.sl", "s.sl")
  
  return(Spatial)
}

# dmta.topology----
#' @title dmta.topology
#' @description Computes topology variables
#' @param sur surface file
#' @param TmpDir temporary folder
#' @param size.x total x length of the surface, in pixels
#' @param size.y total y length of the surface, in pixels
#' @param size.n in case type = "multi", the number of cells for the calculation of heterogeneity
#' @param type character vector indicating whether a single value should be calculated for the whole surface ("single"); or if multiple values should be calculated for each n cells ("multi")
#' @return A list containing the .sur file, the type (topology), Sk1, Sk2, Smc1, Smc2, Snb1, Snb2 and Sh
#' @examples
#' #to do
#' tmp <- tempdir()
#' sur <- system.file("tests/sur/test_surf2.sur", package = "trident")
#'
#' ResTop <- dmta.topology(sur = sur, TmpDir = tmp, size.x = 256,
#'                                                  size.y = 256, size.n = 256, type = "single")
#'
#' dplyr::glimpse(ResTop)
#'
#' ResTopMulti <- dmta.topology(sur = sur, TmpDir = tmp, size.x = 256,
#'                                                       size.y = 256, size.n = 64, type = "multi")
#'
#' dplyr::glimpse(ResTopMulti)
#'
#' @export
dmta.topology <- function(sur, TmpDir, size.x = 256, size.y = 256, size.n = 256, type = "single") {

  #1-Preparation: move files to tmp
    
  Tmp <- stringr::str_replace_all(TmpDir, "\\\\", "/")
  Sur <- stringr::str_replace_all(sur, "\\\\", "/")

  NameSur <- unlist(strsplit(utils::tail(unlist(strsplit(sur, "\\\\")), 1), ".sur"))

  PrgPath <- system.file("extdata", "structure", "prg", "prg.exe", package = "trident")
  if (PrgPath == "") {PrgPath = "inst/extdata/structure/prg/prg.exe"}
  
  file.copy(from = PrgPath, to = Tmp)

  if (file.exists(file.path(Tmp, 'results_topology.txt'))) {
    file.remove(file.path(Tmp, 'results_topology.txt'))
  }
  if (file.exists(file.path(Tmp, 'results_faces.txt'))) {
    file.remove(file.path(Tmp, 'results_faces.txt'))
  }
  
  #2-Recoding
  
  switch(type,
    "single" = {
      Sample.size <- "-0001"
    },
    "multi"  = {
      Sample.size <- paste0("+", size.n)
         },
    stop("type must be 'single' or 'multi'")
  )
  
  #3-Build the scripts

  Myscript <- glue::glue("
VERBOSES
.false.
.false.
'{file.path(Tmp, 'deroulement.txt')}'
 +006
'{file.path(Tmp, 'sortie.txt')}'
DEBUT___
    NB_PROCS
    -1
    LECT_BAS
    '{Sur}'
    .false.
    .false.
    TAB_BOOT
        +{size.x}
        +{size.y}
        {Sample.size}
    STA_LOOP
        +0001 {Sample.size}
        ANALYSES
            'topology'
            '{file.path(Tmp, 'results_topology.txt')}'
            .true.
            -50
    END_LOOP
    TAB_BOOT
        +{size.x}
        +{size.y}
        {Sample.size}
    STA_LOOP
        +0001 {Sample.size}
        ANALYSES
            'facettes'
            '{file.path(Tmp, 'results_faces.txt')}'
            .true.
            -50
    END_LOOP
FIN_____
")
  
  utils::write.table(Myscript, file = file.path(Tmp, "topology_analysis.f90"), quote = FALSE, row.names = FALSE, col.names = FALSE)

  #4-Run the script
  
  system2(command = file.path(Tmp, "prg.exe"), args = file.path(Tmp, "topology_analysis.f90"), stdout = TRUE)


  #5-Scan and return the results
  
  Scanned  <- scan(file = file.path(Tmp, "results_topology.txt"), what = "character()")
print(Scanned)
  Scanned2 <- scan(file = file.path(Tmp, "results_faces.txt"),    what = "character()")
print(Scanned2)
  Results  <- t(matrix(Scanned [-(1:which(stringr::str_detect(Scanned,  "\\.sur")))], nrow = 12))
  Results2 <- t(matrix(Scanned2[-(1:which(stringr::str_detect(Scanned2, "\\.sur")))], nrow =  4))
  
  idx      <- which(stringr::str_detect(Scanned, "\\.sur"))[1] # to get the index of the line containing the .sur file name,
                                                               # which is the first line of the results file. This is used
                                                               # to extract the file name for the output list.
  Filename <- basename(Scanned[idx])
  
  Topology <- list(file = Filename,
                   type = "topology",
                   Sk1  = as.numeric(Results [, 3]),
                   Sk2  = as.numeric(Results [, 6]),
                   Smc1 = as.numeric(Results [, 2]),
                   Smc2 = as.numeric(Results [, 5]),
                   Snb1 = as.numeric(Results [, 1]),
                   Snb2 = as.numeric(Results [, 4]),
                   Sh   = as.numeric(Results2[, 1]))

  names(Topology) <- c("File", "Type", "Sk1", "Sk2", "Smc1", "Smc2", "Snb1", "Snb2", "Sh")
  
  return(Topology)
  
}

#' polynom.sur
#' @title polynom.sur
#' @description A function to remove a given polynomial from a surface
#' @param sur surface file
#' @param TmpDir temporary folder
#' @param deg the polynomial degree to be subtracted to the surface
#' @param path logical, indicates if the path of the cleaned surface should be returned as a character string in R
#' @return a cleaned surface, with a path to its current location if path = TRUE (default)
#' @export
#' @examples
#' tmp <- tempdir()
#' sur <- system.file("tests/sur/test_surf.sur", package = "trident")
#'
#' ResPol <- polynom.sur(sur = sur, TmpDir = tmp, deg = 8, path = TRUE)
polynom.sur <- function(sur, TmpDir, deg = 8, path = TRUE) {

  # Preparation: move files to tmp
  Tmp <- stringr::str_replace_all(TmpDir, "\\\\", "/")
  Sur <- stringr::str_replace_all(sur, "\\\\", "/")

  NameSur <- unlist(strsplit(utils::tail(unlist(strsplit(sur, "\\\\")), 1), ".sur"))

  PrgPath <- system.file("extdata", "structure", "prg", "prg.exe", package = "trident")
  if (PrgPath == "") {PrgPath = "inst/extdata/structure/prg/prg.exe"}
  
  file.copy(from = PrgPath, to = Tmp)

  # Build the script
  
  Myscript <- glue::glue("
VERBOSES
.false.
.false.
'{file.path(Tmp, 'deroulement.txt')}'
 +006
'{file.path(Tmp, 'sortie.txt')}'
DEBUT___
    NB_PROCS
    -1
    LECT_BAS
    '{Sur}'
    .false.
    .false.
     SMOOTH__
     LSSQ_IMG
     +000
     +000
     '{file.path(Tmp, 'results.txt')}'
     {paste0('+', deg)} {paste0('+', deg)}
     .true.
     .false.
FIN_____
")

  # Write the script to the Tmp directory
  utils::write.table(Myscript, file = file.path(Tmp, "polynom.f90"), quote = FALSE, row.names = FALSE, col.names = FALSE)

  # Run the script
  system2(command = file.path(Tmp, "prg.exe"), args = file.path(Tmp, "polynom.f90"), stdout = TRUE)

  # ...return path
  if (path){
    Path <- file.path(dirname(Sur), paste0(NameSur, "_X1_00", deg, "_Y1_00", deg,".sur"))
    return(Path)
  }

  
}

# trident.hetero----
#' @title trident.hetero
#' @description Heterogeneity of dmta variables
#' @param x A numeric vector
#' @param var.name A character string defining the name of the variable from which heterogeneity should be computed; default 'X'
#' @return A data frame of parameters assessing heterogeneity
#' @export
#' @examples
#'
#' x <- c(
#'   12, 15, NA, 18, 21, -14, NA, 19, 23, 17,
#'   16, 20, NA, 22, 24,  13, 11, NA, 25, 26,
#'   27, 28, 29, NA, 30, -10,  9,  8,  7,  6
#' )
#'
#' DFstat <- trident.hetero(x, var.name = "ExampleVariable")
#'
#' dplyr::glimpse(DFstat)
#'
trident.hetero <- function(x, var.name ="X") {
  
  if (!is.numeric(x)) stop("x has to be a numeric vector")
  if (!is.vector(x))  stop("x has to be a numeric vector")
  
  Results <- data.frame(min    = min(x, na.rm = TRUE),
                        max    = max(x, na.rm = TRUE),
                        sd     = stats::sd(x, na.rm = TRUE),
                        mean   = mean(x, na.rm = TRUE),
                        
                        median = as.numeric(stats::quantile(x, 0.50, na.rm = TRUE)),
                        fst.05 = as.numeric(stats::quantile(x, 0.05, na.rm = TRUE)),
                        lst.05 = as.numeric(stats::quantile(x, 0.95, na.rm = TRUE)),
                        
                        min.05 = mean(x[which(x <= stats::quantile(x, 0.05, na.rm = TRUE))], na.rm = TRUE),
                        max.05 = mean(x[which(x >= stats::quantile(x, 0.95, na.rm = TRUE))], na.rm = TRUE),
                        
                        fst.25 = as.numeric(stats::quantile(x, 0.25, na.rm = TRUE)),
                        lst.25 = as.numeric(stats::quantile(x, 0.75, na.rm = TRUE)),
                        
                        min.25 = mean(x[which(x <= stats::quantile(x, 0.25, na.rm = TRUE))], na.rm = TRUE),
                        max.25 = mean(x[which(x >= stats::quantile(x, 0.75, na.rm = TRUE))], na.rm = TRUE),
                        
                        skw    = DescTools::Skew(x, na.rm = TRUE),
                        kurt   = DescTools::Kurt(x, na.rm = TRUE))
  return(Results)
}

