# WARNING - Generated by {fusen} from dev/flat_graphics-functions.Rmd: do not edit by hand # nolint: line_length_linter.

#' @title Graphics functions
#' @description Internal grouping function
#' @noRd
graphics <- function() {
  NULL
}

#' plot_bivariate
#' @title plot_bivariate
#' @description Bivariate PCA Plot with Active and Supplementary Individuals
#' @param pca_result A PCA object (from FactoMineR).
#' @param factors A data frame containing categorical variables for the individuals.
#' @param factor_col String. The name of the column in `factors` to use for grouping.
#' @param pc_x Integer. The principal component to plot on the X-axis (default: 1).
#' @param pc_y Integer. The principal component to plot on the Y-axis (default: 2).
#'
#' @return A ggplot2 object.
#' @export
#' @examples
#' data(decathlon2, package = "factoextra")
#'
#' res.pca <- FactoMineR::PCA(
#'     decathlon2[1:23, 1:12],
#'     quanti.sup = 11:12,
#'     ind.sup    = 20:23,
#'     graph      = FALSE)
#'
#'
#' factors <- decathlon2[ "Competition"]
#'
#' factor_col <- "Competition"
#'
#' plot_bivariate(
#'   pca_result = res.pca,
#'   factors = factors,
#'   factor_col = "Competition",
#'   pc_x = 1,
#'   pc_y = 2
#' )
plot_bivariate <- function(pca_result, factors, factor_col, pc_x = 1, pc_y = 2) {
  
  # 1. Basic security checks
  if (!factor_col %in% colnames(factors)) {
    stop("factor_col must be a column name of factors")
  }
  
  # 2. Extract active individuals data
  ind        <- factoextra::get_pca_ind(pca_result)
  ind_df     <- as.data.frame(ind$coord)
  ind_df$ind <- rownames(ind_df)
  
  # Map grouping factor
  ind_df$group <- as.character(factors[rownames(ind_df), factor_col])
  
  # 3. Handle supplementary individuals
  has_sup <- !is.null(pca_result$ind.sup)
  label_sup <- "supp. ind."
  
  if (has_sup) {
    ind_sup       <- as.data.frame(pca_result$ind.sup$coord)
    ind_sup$ind   <- rownames(ind_sup)
    ind_sup$group <- label_sup
  }
  
  # 4. Color management (Handling RColorBrewer's n < 3 limitation)
  unique_groups <- unique(ind_df$group)
  n_groups      <- length(unique_groups)
  
  # Ensure brewer.pal receives at least 3 to avoid warnings
  base_cols <- if(n_groups < 3) {
    RColorBrewer::brewer.pal(3, "Dark2")[1:n_groups]
  } else {
    RColorBrewer::brewer.pal(min(n_groups, 8), "Dark2")
  }
  
  # Build named color palette (Active groups + Black for supplementary)
  my_palette <- stats::setNames(base_cols, unique_groups)
  if(has_sup) my_palette <- c(my_palette, stats::setNames("black", label_sup))

  # 5. Core plotting
  x_col <- paste0("Dim.", pc_x)
  y_col <- paste0("Dim.", pc_y)
  
  p <- ggplot2::ggplot(ind_df, ggplot2::aes(x = .data[[x_col]], y = .data[[y_col]])) +
    
    # Ellipses (Active only, legend hidden to prevent duplication)
    ggplot2::stat_ellipse(
      ggplot2::aes(fill = .data$group),
      geom = "polygon", alpha = 0.2, color = NA, show.legend = FALSE
    ) +
    
    # Active points
    ggplot2::geom_point(ggplot2::aes(color = .data$group), size = 2.5, alpha = 0.9) +
    
    # Active labels
    ggrepel::geom_text_repel(
      ggplot2::aes(label = ind, color = .data$group),
      size = 3, show.legend = FALSE
    )

  # 6. Add supplementary layers if present
  if (has_sup) {
    
    p <- p +
      
      ggplot2::geom_point(
        data = ind_sup,
        ggplot2::aes(color = .data$group),
        size = 3, shape = 17
      ) +
      
      ggrepel::geom_text_repel(
        data = ind_sup,
        ggplot2::aes(label = ind, color = .data$group),
        size = 3, show.legend = FALSE
      )
    
  }

  # 7. Scales and final theme
  p +
    ggplot2::geom_hline(yintercept = 0, linetype = "dashed", color = "grey70") +
    ggplot2::geom_vline(xintercept = 0, linetype = "dashed", color = "grey70") +
    
    # Unified scale management
    ggplot2::scale_color_manual(values = my_palette) +
    ggplot2::scale_fill_manual( values = my_palette) +
    
    ggplot2::labs(
      x = paste0("Dim ", pc_x, " (", round(pca_result$eig[pc_x, 2], 1), "%)"),
      y = paste0("Dim ", pc_y, " (", round(pca_result$eig[pc_y, 2], 1), "%)"),
      colour = factor_col
    ) +
    
    ggplot2::theme_minimal(base_size = 13) +
    ggplot2::theme(
      panel.grid      = ggplot2::element_blank(),
      axis.line       = ggplot2::element_line(color = "black"),
      legend.position = "right"
    ) #+
    
    #ggplot2::coord_equal()
}


#' plot_corcircle
#' @title plot_corcircle
#' @description
#' Creates a correlation circle plot from a PCA result (typically from
#' \code{FactoMineR::PCA}), displaying active variables colored by their
#' contribution to the selected principal components and supplementary
#' quantitative variables in a distinct color.
#' The function enhances the default visualization from \code{factoextra}
#' by:
#' \itemize{
#'   \item coloring active variables according to their contribution
#'   \item adding supplementary quantitative variables manually
#'   \item improving label readability using \code{ggrepel}
#'   \item applying a clean \code{ggplot2} theme suitable for publication
#' }
#' @param pca_result A PCA object of class \code{PCA} generated by
#'   \code{FactoMineR::PCA}.
#' @param pc_x Integer. Index of the principal component to display on the x-axis.
#'   Typically 1 for Dim.1.
#' @param pc_y Integer. Index of the principal component to display on the y-axis.
#'   Typically 2 for Dim.2.
#' @return
#' A \code{ggplot2} object representing the PCA correlation circle with:
#' \itemize{
#'   \item active variables colored by contribution
#'   \item supplementary quantitative variables in a fixed color
#'   \item labeled arrows for all variables
#' }
#' @export
#' @examples
#' data(decathlon2, package = "factoextra")
#'
#' res.pca <- FactoMineR::PCA(
#'     decathlon2[1:23, 1:12],
#'     graph      = FALSE)
#'
#' plot_corcircle(pca_result = res.pca, pc_x = 1, pc_y = 2)
#'     
#' res.pca <- FactoMineR::PCA(
#'     decathlon2[1:23, 1:12],
#'     quanti.sup = 11:12,
#'     ind.sup    = 20:23,
#'     graph      = FALSE)
#'
#' plot_corcircle(pca_result = res.pca, pc_x = 1, pc_y = 2)
#'     

plot_corcircle <- function(pca_result, pc_x, pc_y) {
    
    x_col <- paste0("Dim.", pc_x)
    y_col <- paste0("Dim.", pc_y)

    # basis
    p <- factoextra::fviz_pca_var(pca_result, col.var = "black", repel = TRUE)

    # active variable
    var            <- factoextra::get_pca_var(pca_result)
    var_df         <- as.data.frame(var$coord)
    var_df$contrib <- rowSums(var$contrib[, 1:2])
    var_df$var     <- rownames(var_df)

    # supplementary variables
    quanti.sup <- NULL
    if (!is.null(pca_result$quanti.sup)) {
      quanti.sup     <- as.data.frame(pca_result$quanti.sup$coord)
      quanti.sup$var <- rownames(quanti.sup)
    }

    p <- p +
      # recolorisation des variables actives
      ggplot2::geom_segment(
        data = var_df, ggplot2::aes(x = 0,
                                    y = 0,
                                    xend = .data[[x_col]],
                                    yend = .data[[y_col]], color = .data$contrib),
        arrow     = ggplot2::arrow(length = ggplot2::unit(0.25, "cm")),
        linewidth = 0.8
      ) +
      
      ggrepel::geom_text_repel(
        data = var_df, ggplot2::aes(x = .data[[x_col]],
                                    y = .data[[y_col]], label = var, color = .data$contrib),
        size = 4
      )
      
    if (!is.null(pca_result$quanti.sup)) {
            
    p <- p +
      # variables supplémentaires (couleur fixe)
      ggplot2::geom_segment(
        data = quanti.sup, ggplot2::aes(x = 0,
                                        y = 0,
                                        xend = .data[[x_col]],
                                        yend = .data[[y_col]]),
        arrow     = ggplot2::arrow(length = ggplot2::unit(0.25, "cm")),
        linewidth = 0.8,
        color     = "#D81B60"
      ) +
  
      ggrepel::geom_text_repel(
        data = quanti.sup, ggplot2::aes(x = .data[[x_col]],
                                        y = .data[[y_col]], label = var),
        color = "#D81B60",
        size  = 4)

      }

    p <- p +
      # axes
      ggplot2::geom_hline(yintercept = 0, linetype = "dashed", color = "grey70") +
      ggplot2::geom_vline(xintercept = 0, linetype = "dashed", color = "grey70") +
      
      # gradient moderne
      ggplot2::scale_color_gradient(
        low  = "#B0BEC5",  # gris clair
        high = "#0D47A1"   # bleu profond
      ) +
      
      ggplot2::labs(
        color = "Contribution (%)",
        x     = paste0("Dim 1 (", round(pca_result$eig[1,2], 1), "%)"),
        y     = paste0("Dim 2 (", round(pca_result$eig[2,2], 1), "%)")
      ) +
      
      ggplot2::theme_minimal(base_size = 13) +
      ggplot2::theme(
        panel.grid      = ggplot2::element_blank(),
        axis.line       = ggplot2::element_line(color = "black"),
        legend.position = "right"
      )
    
    p
}

#' Plot Scree Plot from PCA Result
#'
#' @title plot_screeplot
#' @description
#' Generates a scree plot (eigenvalues bar plot) from a PCA result object
#' produced by \code{FactoMineR::PCA}. The plot shows the percentage of
#' variance explained by each principal component.
#' @param pca_result A PCA result object returned by \code{FactoMineR::PCA}.
#' @return A \code{ggplot2} object representing the scree plot.
#' @export
#' @examples
#' data(iris)
#'
#' res_pca <- FactoMineR::PCA(iris[, 1:4], graph = FALSE)
#'
#' plot_screeplot(res_pca)
plot_screeplot <- function(pca_result) {

  factoextra::fviz_eig(
    pca_result,
    addlabels = TRUE,
    ylim      = c(0, max(pca_result$eig[, 2])),
    barfill   = "lightgoldenrod",
    barcolor  = "lightgoldenrod3"
  )

}

#' prepare_pca_data
#' @title prepare_pca_data
#' @description Prepare data for PCA by separating numeric and factor columns and optionally reordering columns.
#' @param df Data frame to process.
#' @param var_order Vector of column names to reorder (or NULL).
#' @return A list with components numerics and factors.
#' @export
#' 
#' @examples
#' df <- data.frame(a = 1:3, b = factor(c("x","y","z")), c = 4:6)
#' prepare_pca_data(df)
#' prepare_pca_data(df, var_order = c("c", "a"))
prepare_pca_data <- function(df, var_order = NULL) {
  numerics <- dplyr::select_if(df, is.numeric)
  factors  <- dplyr::select_if(df, is.factor)

  if (!is.null(var_order)) numerics <- numerics[, var_order, drop = FALSE]

  list(numerics = numerics, factors = factors)
}

#' Render a distribution plot (violin or boxplot) for a given data frame and specified variables.
#'
#' @title Render a distribution plot
#' @description This function creates a distribution plot (either a violin plot or a boxplot) for a specified data frame and variables. The user can choose the type of plot and customize the colors.
#' @param df A data frame containing the variables to plot.
#' @param x_var A character string specifying the name of the categorical variable
#'        to be mapped on the x-axis (grouping variable).
#' @param y_var A character string specifying the name of the numeric variable
#'        to be mapped on the y-axis (response variable).
#' @param type A character string specifying the type of plot to produce.
#'        Must be either `"violin"` (default) or `"boxplot"`.
#' @return A ggplot object representing the distribution plot.
#' @export
#' @examples
#' data(iris)
#'
#' renderDistributionPlot(
#'   df    = iris,
#'   x_var = "Species",
#'   y_var = "Sepal.Length",
#'   type  = "violin"
#' )
renderDistributionPlot <- function(df, x_var, y_var, type = "violin") {
  
  colors = rep(c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7"), 3) #24 levels max

  # Graphic base
  p <- ggplot2::ggplot(df, ggplot2::aes(x = .data[[x_var]], y = .data[[y_var]], fill = .data[[x_var]]))
  
  # Add the appropriate geometry based on the chosen type
  if (type == "violin") {
      
    p <- p + ggplot2::geom_violin(scale = "area", linewidth = 0.5)
    
  } else {
      
    p <- p + 
      ggplot2::geom_boxplot(outlier.shape = NA) +
      ggplot2::geom_jitter(ggplot2::aes(col = .data[[x_var]]), 
                           position = ggplot2::position_jitterdodge(jitter.width = 0.5)) +
      ggplot2::scale_color_manual(values = colors)
    
  }
  
  # Design and theme
  p <- p + 
    ggplot2::scale_fill_manual(values = if(type == "boxplot") colorspace::lighten(colors, 0.7) else colors) +
    ggplot2::labs(x = x_var, y = y_var) +
    ggplot2::theme_bw() + 
    ggplot2::theme(
      text = ggplot2::element_text(family = "serif"),
      legend.position  = "right",
      legend.title     = ggplot2::element_text(size = 14),
      legend.text      = ggplot2::element_text(size = 12, face = "bold"),
      axis.title       = ggplot2::element_text(size = 14),
      axis.text        = ggplot2::element_text(size = 12, angle = 90, hjust = 0.5),
      axis.text.x      = ggplot2::element_blank(),
      panel.grid.major = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      panel.background = ggplot2::element_rect(fill = "#ffffff", colour = "#000000")
    )
  
  return(p)
  
}

#' run_pca
#' @title run_pca
#' @description Run a PCA using the active numeric variables, with optional supplementary
#' variables (quanti.sup) and supplementary individuals (ind.sup). The function
#' assembles the data matrix according to the presence of these extras and then
#' calls FactoMineR::PCA.
#' @param numerics  data.frame of the active numeric variables.
#' @param active_cols Names of the active columns selected for the PCA.
#' @param supp_vars Names of the supplementary variables (character vector, may be NULL).
#' @param supp_inds data.frame of supplementary individuals (may be NULL).
#' @return PCA object (FactoMineR) containing the results.
#' @export
#' @examples
#' data(iris)
#'
#' # numeric columns
#' iris_num <- iris[, 1:4]
#'
#' # active columns
#' train <- iris_num[1:100, ]
#'
#' # supplementary individuals
#' supp_inds <- iris_num[101:110, ]
#'
#' # PCA
#' res <- run_pca(
#'   numerics    = train,
#'   active_cols = c("Sepal.Length", "Sepal.Width"),
#'   supp_vars   = c("Petal.Length", "Petal.Width"),
#'   supp_inds   = supp_inds
#' )
#'
#' # results
#' summary(res)
run_pca <- function(numerics, active_cols, supp_vars = NULL, supp_inds = NULL) {

    # Detect presence of supplementary variables and supplementary individuals
    has_supp_vars <- length(supp_vars) > 0
    has_supp_inds <- !is.null(supp_inds)

    # Number of active columns to determine indexing for supplementary data
    n_active <- length(active_cols)

    # Columns for PCA include active columns and, if provided, supplementary variables
    pca_cols <- if (has_supp_vars) {
        c(active_cols, supp_vars)
    } else {
        active_cols
    }

    # Subset the numerics to the selected PCA columns
    pca_data <- numerics[, pca_cols, drop = FALSE]

    # If supplementary individuals are provided, append their data
    if (has_supp_inds) {
        supp_data <- supp_inds[, pca_cols, drop = FALSE]
        pca_data  <- dplyr::bind_rows(pca_data, supp_data)
    }

    # Number of rows in the original active data (used for ind.sup indexing)
    n_rows_active <- nrow(numerics)

    # Run PCA with optional supplementary parameters
    FactoMineR::PCA(
        pca_data,
        graph       = FALSE,
        quanti.sup  = if (has_supp_vars) (n_active + 1):(n_active + length(supp_vars)) else NULL,
        ind.sup     = if (has_supp_inds) (n_rows_active + 1):nrow(pca_data) else NULL
    )
}

