# WARNING - Generated by {fusen} from dev/flat_statistics-functions.Rmd: do not edit by hand # nolint: line_length_linter.

#' multicheck
#' @title multicheck
#' @description Perform various statistical checks on numeric variables against a grouping factor.
#' @param df A data frame composed entirely of numeric variables.
#' @param y A factor used as the grouping variable.
#' @param alpha Significance level (default: 0.05).
#' @importFrom foreach foreach %dopar% %:%
#' @return A named list of p-values, ratios, and decision flags for each variable.
#' @export
#' @examples
#' csv <- system.file("tests/csv/Vars.csv", package = "trident")
#'
#' df <- read.csv(file = csv, header = TRUE, as.is = TRUE, row.names = NULL)
#'
#' fa <- as.factor(c(rep("A", 15), rep("B", 15), rep("C", 15)))
#'
#' df[] <- lapply(df, as.numeric)
#'
#' DFstat <- multicheck(df = df, y = fa, alpha = 0.05)
#'
#' csv <- system.file("tests/csv/DFstat.csv", package = "trident")
#'
#' write.csv(DFstat, file = csv, row.names = FALSE, quote = FALSE)
#'

multicheck <- function(df, y, alpha = 0.05) {

  # --- Input validation -------------------------------------------------------
  if (!is.data.frame(df)) {
    stop("'df' must be an object of class data.frame (see ?is.data.frame).")
  }
  if (!is.factor(y)) {
    stop("'y' must be a factor.")
  }
  if (any(!apply(df, 2, is.numeric))) {
    stop("All columns of 'df' must be numeric.")
  }

  # --- Data preparation -------------------------------------------------------
  mydf <- data.frame(y = as.factor(y), df)
  mydf <- mydf[is.finite(rowSums(mydf[, -1])), ] # Retain only rows with finite values in numeric columns

  my_matrix <- t(matrix(
                        data  = unlist(mydf[, -1]),
                        ncol  = ncol(df)
                       )
                 )
  
  my_factor <- mydf[, 1]
  n_vars    <- nrow(my_matrix)
  var_names <- colnames(df)

  # --- Parallel backend setup -------------------------------------------------
  cl <- snow::makeSOCKcluster(max(1L, parallel::detectCores() - 1L)) # Leave at least one core free
  
  doSNOW::registerDoSNOW(cl)
  
  on.exit(snow::stopCluster(cl), add = TRUE)  # Ensure cluster is stopped when function exits, even if an error occurs

  # --- Statistical tests ------------------------------------------------------

  # Welch ANOVA, with error handling to return NA for any variable that causes an error (e.g., due to insufficient data)
  # Robust to non-normality and heteroscedasticity, but less powerful than OneWay Anova when assumptions are met.
  p_anova.W <- foreach::foreach(
    i        = seq_len(n_vars),
    .combine = "c"
  ) %dopar% {
    result <- tryCatch(
      stats::oneway.test(
        my_matrix[i, ] ~ my_factor,
        na.action = "na.omit"
      )$p.value,
      error = function(e) NA_real_
    )
    if (!is.numeric(result) || length(result) != 1L) NA_real_ else result
  }

  # Kruskal-Wallis test (robust to non-normality)
  p_kruskal <- foreach::foreach(
    i        = seq_len(n_vars),
    .combine = "c"
  ) %dopar% {
    stats::kruskal.test(my_matrix[i, ] ~ my_factor)$p.value
  }

  # ANOVA residuals (for normality and homoscedasticity tests)
  residuals_list <- foreach::foreach(
    i = seq(2L, ncol(mydf))
  ) %dopar% {
    stats::aov(mydf[, i] ~ mydf[, 1])$residuals
  }
  residuals_mat <- t(matrix(
    data = unlist(residuals_list),
    ncol = n_vars
  ))

  # Anderson-Darling test; not used for decision tree
  p_anderson <- foreach::foreach(
    i        = seq_len(n_vars),
    .combine = "c"
  ) %dopar% {
    nortest::ad.test(residuals_mat[i, ])$p.value
  }

  # Bartlett test; only used if normality is TRUE in the decision tree
  p_bartlett <- foreach::foreach(
    i        = seq_len(n_vars),
    .combine = "c"
  ) %dopar% {
    stats::bartlett.test(residuals_mat[i, ] ~ my_factor)$p.value
  }

  # Levene test; only used if normality is nearly in the decision tree
  p_levene <- foreach::foreach(
    i        = seq_len(n_vars),
    .combine = "c"
  ) %dopar% {
    car::leveneTest(residuals_mat[i, ], my_factor, center = "median")$`Pr(>F)`[1]
  }

  # Shapiro-Wilk test; only used for normality assessment in the decision tree
  p_shapiro <- foreach::foreach(
    i        = seq_len(n_vars),
    .combine = "c"
  ) %dopar% {
    stats::shapiro.test(residuals_mat[i, ])$p.value
  }

  # Asymmetry Ratio (bootstrap BCA)
  # The authors of DescTools (Andri Signorell) explicitly chose bootstrap as the default/recommended approach
  # for the confidence interval of Skew() and Kurt()
  skw_ratio <- foreach::foreach(
    i        = seq_len(n_vars),
    .combine = "c"
  ) %dopar% {

  withr::with_seed(12, { # to ensure reproducibility of the bootstrap results, which can vary across runs due to random resampling. Setting a seed allows for consistent results when the function is run multiple times.
    skw <- DescTools::Skew(
      x          = residuals_mat[i, ],
      method     = 3,
      conf.level = 0.95,
      ci.type    = "bca",
      R          = 1000
    )
    result <- abs(skw[[1]] / (skw[[3]] - skw[[2]]))
  })
  }

  # Inter-group ratio variances
  variance_per_cat <- foreach::foreach(
    j        = seq_along(levels(my_factor)),
    .combine = "cbind"
  ) %:%
    foreach::foreach(
      i        = seq_len(n_vars),
      .combine = "c"
    ) %dopar% {
      stats::var(residuals_mat[i, which(my_factor == levels(my_factor)[j])])
    }

  var_ratio <- foreach::foreach(
    i        = seq_len(n_vars),
    .combine = "c"
  ) %dopar% {
    mins <- min(variance_per_cat[i, ])
    if (mins != 0) {
      max(variance_per_cat[i, ]) / mins
    } else {
      NA_real_
    }
  }

  # --- decision tree ------------------------------------------------------

  is_normal        <- character(n_vars)
  is_homoscedastic <- character(n_vars)
  is_discriminant  <- character(n_vars)

  # Normalité (via Shapiro-Wilk et ratio d'asymétrie)
  is_normal[p_shapiro >  alpha]                   <- "TRUE"
  is_normal[p_shapiro <= alpha & skw_ratio <  2]  <- "nearly"
  is_normal[p_shapiro <= alpha & skw_ratio >= 2]  <- "FALSE"

  # Heteroscedsasticity is set FALSE if normality is FALSE
  is_homoscedastic[is_normal == "FALSE"] <- "FALSE"

  # Homoscédasticité Bartlett
  is_homoscedastic[is_normal == "TRUE"    & p_bartlett >  alpha] <- "TRUE"
  is_homoscedastic[is_normal == "TRUE"    & p_bartlett <= alpha & var_ratio <= 3] <- "nearly"
  is_homoscedastic[is_normal == "TRUE"    & p_bartlett <= alpha & var_ratio >  3] <- "FALSE"

  # Homoscedasticity Levene
  is_homoscedastic[is_normal == "nearly"  & p_levene   >  alpha] <- "TRUE"
  is_homoscedastic[is_normal == "nearly"  & p_levene   <= alpha] <- "FALSE"


  # Discrimination ability
  is_discriminant[] <- "FALSE"
  
  homo_ok <- is_homoscedastic %in% c("TRUE", "nearly")

  is_discriminant[homo_ok & p_anova.W < alpha] <- "TRUE"

  # --- Results --------------------------------------------------------------
  list(
    variable         = var_names,
    anderson_p.value = p_anderson, # not used
    anova_p.value    = p_anova.W,
    bartlett_p.value = p_bartlett,
    kruskal_p.value  = p_kruskal,  # not used
    levene_p.value   = p_levene,
    shapiro_p.value  = p_shapiro,
    skewness.ratio   = skw_ratio,
    variance.ratio   = var_ratio,
    is.normal        = is_normal,
    is.homoscedastic = is_homoscedastic,
    is.discriminant  = is_discriminant
  )
}

# run_posthoc
#' @title run_posthoc
#' @description Ranks the top 3 variables capable of discriminating categories for each pair of factor levels.
#' @param x Numeric vector of observations.
#' @param y Factor grouping variable.
#' @param method Character. Post-hoc method (e.g. "hsd", "lsd").
#' @param alpha Numeric. Significance threshold.
#'
#' @return Numeric vector containing: p-values, mean significant p-value, geometric mean,
#'         number of significant tests.
#' @export
#' @examples
#' data("iris")
#'
#' res <- run_posthoc( x = iris$Sepal.Length,
#'                     y = iris$Species,
#'                     method = "hsd",
#'                     alpha = 0.05)
#'
#' cat("p_vals: ",    res[1:3], "\n")
#' cat("avg_p:  ",    res[4], "\n")
#' cat("geo_p:  ",    res[5], "\n")
#' cat("n_signif:  ", res[6], "\n")
 run_posthoc <- function(x, y, method, alpha) {
      
    ph     <- DescTools::PostHocTest(
                stats::aov(x ~ y),
                method = method,
                conf.level = 1 - alpha)
    
    p_vals <- as.numeric(ph[[1]][, "pval"])
    
    signif_p <- p_vals[p_vals < alpha]
    
    # Calculate metrics
    avg_p    <- if(length(signif_p) > 0) mean(signif_p) else 1
    geo_p    <- if(length(signif_p) > 0) exp(mean(log(signif_p))) else 1
    n_signif <- length(signif_p)
    
    return(c(p_vals, avg_p, geo_p, n_signif))
    
  }

#' @title Statistics functions
#' @description Internal grouping function
#' @noRd
statistics <- function() {
  NULL
}

# trident.arrange
#' @title trident.arrange
#' @description Computes multiple statistical tests (ANOVA, Kruskal, Post-hoc) to rank variables.
#' @param df A data frame of numeric values.
#' @param y A factor vector.
#' @param by Sorting parameter. See documentation for available options.
#' @param alpha Significance level (default 0.05).
#' @param byngr Logical: sort by the number of significantly different groups?
#' @param geomean Logical: use geometric mean for p-values?
#' @param gp.priority Numeric vector to reorder factor levels.
#' @return A data frame of variables ranked by the selected parameter.
#' @export
#' @examples
#' library(dplyr)
#'
#' df <- iris[, 1:4]
#' y  <- iris$Species
#'
#' res <- trident.arrange( df    = df,
#'                         y     = y,
#'                         by    = "f.stat",
#'                         alpha = 0.05
#'                       )
#' head(res)
trident.arrange <- function(df, y, by = "hsd.mean.p.value", alpha = 0.05, 
                            byngr = FALSE, geomean = FALSE, 
                            gp.priority = seq_along(levels(y))) {
  
  # 1. Validations ----
  stopifnot(
    "df must be a data frame"           = is.data.frame(df),
    "y must be a factor"                = is.factor(y),
    "All columns in df must be numeric" = all(sapply(df, is.numeric))
  )

  # 2. Factor Levels Management ----
  all_levels <- levels(y)
  new_levels <- unique(c(all_levels[gp.priority], all_levels))
  
  y <- factor(y, levels = new_levels)

  # 3. Data Cleaning ----
  clean_df <- data.frame(y = y, df) %>%
    dplyr::filter(dplyr::if_all(where(is.numeric), is.finite))
  
  # Extract numeric matrix for faster computation
  mat   <- as.matrix(clean_df[, -1])
  y_vec <- clean_df$y

  # 4. Statistical Computations ----
  
  # Apply tests across all columns
  stats_list <- lapply(colnames(clean_df)[-1], function(col_name) {
    x <- clean_df[[col_name]]
    
    # ANOVA & Kruskal
    aov_res <- stats::oneway.test(x ~ y_vec)
    k_res   <- stats::kruskal.test(x ~ y_vec)
    
    # Post-Hocs
    hsd_res <- run_posthoc(x, y_vec, "hsd", alpha )
    lsd_res <- run_posthoc(x, y_vec, "lsd", alpha )
    
    c(f.stat      = as.numeric(aov_res$statistic), 
      aov.p.value = aov_res$p.value,
      k           = as.numeric(k_res$statistic), 
      k.p.value   = k_res$p.value,
      hsd         = hsd_res,
      lsd         = lsd_res)
  })

  # 5. Result Assembly ----
  res_table           <- as.data.frame(do.call(rbind, stats_list))
  rownames(res_table) <- colnames(clean_df)[-1]
 
  # Generate dynamic column names for post-hocs
  group_names <- utils::combn(levels(y_vec), 2, paste, collapse = ".vs.")
  suffix      <- c(group_names, "mean", "geomean", "signif.groups")
  
  colnames(res_table)[5:(4 + length(suffix))] <- paste0("hsd.", suffix)
  colnames(res_table)[  (5 + length(suffix)):ncol(res_table)] <- paste0("lsd.", suffix)

  # 6. Sorting Logic (Arrange) ----
  sort_col <- switch(by,
    "f.stat"           = "f.stat",
    "aov.p.value"      = "aov.p.value",
    "k"                = "k",
    "k.p.value"        = "k.p.value",
    "hsd.mean.p.value" = if(geomean) "hsd.geomean" else "hsd.mean",
    "lsd.mean.p.value" = if(geomean) "lsd.geomean" else "lsd.mean",
    "hsd.p.value"      = colnames(res_table)[5], # First pair
    "lsd.p.value"      = colnames(res_table)[(5 + length(suffix))] # First pair
  )

  decreasing <- !grepl("p.value|mean|geomean", sort_col) # Sort descending for stats, ascending for p-values
  
  if (byngr && grepl("hsd|lsd", by)) {
    group_col <- if(grepl("hsd", by)) "hsd.signif.groups" else "lsd.signif.groups"
    # Secondary sort: Signif groups (desc) then p-value (asc)
    res_table <- res_table[order(-res_table[[group_col]], res_table[[sort_col]]), ]
  } else {
    res_table <- res_table[order(res_table[[sort_col]], decreasing = decreasing), ]
  }

  return(res_table)
  
}


# trident.boxcox ----
#' @title trident.boxcox
#' @description Transforms the variables of a data.frame using the Box-Cox formula,
#'   estimating the optimal lambda parameter for each variable via ANOVA.
#' @param df A data.frame of numeric values.
#' @param y A factor representing the grouping variable.
#' @param list.lambda Logical. If TRUE, the list of estimated lambdas is
#'   included in the results. Defaults to FALSE.
#' @return A list containing:
#'   \item{boxcox}{A data.frame of transformed values.}
#'   \item{lambda}{(optional) A numeric vector of estimated lambdas.}
#' @export
#' @examples
#' csv <- system.file("tests/csv/Example_BoxCox.csv", package = "trident")
#'
#' df <- read.csv(file = csv, header = TRUE, as.is = TRUE, row.names = NULL)
#'
#' fact <- as.factor(c(rep("A", 15), rep("B", 15), rep("C", 15)))
#'
#' for (i in seq_len(ncol(df))) {
#'
#'     stats::aov(df[, i] ~ fact)$residuals -> residuals
#'
#'     p.value <- stats::shapiro.test(residuals)$p.value
#'     
#'     print(p.value)
#' }
#'
#' df_trans  <- trident.boxcox(df = df, y = fact, list.lambda = TRUE)$boxcox
#' df_lambda <- trident.boxcox(df = df, y = fact, list.lambda = TRUE)$lambda
#'
#' for (i in seq_len(ncol(df))) {
#'
#'     stats::aov(df_trans[, i] ~ fact)$residuals -> residuals
#'
#'     p.value <- stats::shapiro.test(residuals)$p.value
#'     
#'     print(c(p.value, df_lambda[i]))
#' }
#'
trident.boxcox <- function(df, y, list.lambda = FALSE) {

  # --- Input validation ---
  if (!is.data.frame(df))
    stop("'df' must be an object of class data.frame.")
  if (!is.factor(y))
    stop("'y' must be a factor.")
  if (!all(vapply(df, is.numeric, logical(1L))))
    stop("All columns of 'df' must be numeric.")
  if (nlevels(y) < 2L)
    stop("'y' must have at least 2 levels.")
  if (nrow(df) != length(y))
    stop("'df' and 'y' must have the same number of observations.")

  # --- Cleaning: remove rows with NA, NaN, Inf, -Inf ---
  mydf <- data.frame(y = y, df)
  mydf <- mydf[is.finite(rowSums(mydf[, -1L, drop = FALSE])), , drop = FALSE] # Retain only rows with finite values in numeric columns

  if (nrow(mydf) == 0L)
    stop("No valid observations remaining after removal of non-finite values.")

  # --- Translation: shift all values above 1 (required by Box-Cox) ---
  translate_above_one <- function(x) x - min(x, na.rm = TRUE) + 1
  mydf[, -1L] <- as.data.frame(lapply(mydf[, -1L, drop = FALSE], translate_above_one)) # Apply translation to all numeric columns, ensuring the result is a data.frame

  # --- Lambda estimation and Box-Cox transformation ---
  n_vars   <- ncol(df)
  mylambda <- vector("numeric", n_vars)
  myboxcox <- mydf[, -1L, drop = FALSE]

  for (i in seq_len(n_vars)) {

    col_data <- mydf[[i + 1L]]

    # Skip constant variables
    if (stats::var(col_data) == 0) next

    aov_formula <- stats::formula(col_data ~ mydf[["y"]])

    # Coarse search for lambda over [-5, 5]
    bc1 <- MASS::boxcox(aov_formula, lambda = seq(-5, 5, by = 0.01),
                        data = mydf, plotit = FALSE)

    # Refinement over the 95% confidence interval
    ci_threshold <- max(bc1$y) - stats::qchisq(0.95, df = 1L) / 2
    lambda_range <- range(bc1$x[bc1$y >= ci_threshold])
    bc2 <- MASS::boxcox(aov_formula,
                        lambda = seq(lambda_range[1L], lambda_range[2L], by = 0.01),
                        data = mydf, plotit = FALSE)

    # Final lambda: midpoint of the refined CI, rounded to 1 decimal place
    ci_range     <- range(bc2$x[bc2$y >= max(bc2$y) - stats::qchisq(0.95, df = 1L) / 2])
    mylambda[i]  <- round(mean(ci_range), digits = 1L)

    # Apply the transformation
    myboxcox[[i]] <- if (mylambda[i] == 0) {
      log(col_data)
    } else {
      (col_data ^ mylambda[i] - 1) / mylambda[i]
    }
  }

  # --- Build and return results ---
  results <- list(boxcox = myboxcox)
  if (list.lambda) results$lambda <- mylambda
  results
}


# trident.top3
#' @title trident.top3s
#' @description Ranks the top 3 variables capable of discriminating categories for each pair of factor levels.
#' @param df A data frame of numeric values.
#' @param y A factor vector.
#' @return A list containing the top 3 variable names and a ranked data frame.
#' @export
#' @examples
#' library(foreach)
#' library(dplyr)
#'
#' df <- mtcars[, c("mpg","disp","hp","drat","wt","qsec")]
#' y  <- factor(mtcars$cyl)
#'
#' res <- trident.top3(df = df, y = y)
#'
#' res$ranked[c("group", "aov.p.value")]
#'
trident.top3 <- function(df, y) {
  
  # 1. Validation of inputs ----
  # Using 'stopifnot' for concise and readable data structure checks
  stopifnot(
    "df must be a data frame"           = is.data.frame(df),
    "y must be a factor"                = is.factor(y),
    "df rows must match y length"       = nrow(df) == length(y),
    "All columns in df must be numeric" = all(sapply(df, is.numeric))
  )

  # 2. Data Cleaning ----
  # Combine y and df, then filter out any rows with non-finite values (NA, NaN, Inf)
  clean_df <- data.frame(y = y, df) %>%
    dplyr::filter(dplyr::if_all(where(is.numeric), is.finite))
  
  # Exit if dataset is empty after cleaning
  if (nrow(clean_df) == 0) stop("No finite rows remaining after cleaning.")

  # 3. Box-Cox Transformation ----
  # Extract numerics (excluding 'y' at col 1) and apply Box-Cox
  numerics_bc           <- trident.boxcox(df = clean_df[, -1], y = clean_df$y)$boxcox
  colnames(numerics_bc) <- paste0(colnames(numerics_bc), ".bc") # Add suffix to indicate Box-Cox transformation

  # 4. Discriminant Filtering ----
  # Check which variables are statistically discriminant
  check_results <- multicheck(df = numerics_bc, y = clean_df$y)
  
  if (!any(as.logical(check_results$is.discriminant))) {
    warning("No discriminant variables found; top3 procedure aborted.")
    return(NULL)
  }
  
  # Keep only discriminant columns
  numerics_filtered <- numerics_bc[, as.logical(check_results$is.discriminant), drop = FALSE]

  # 5. Top 3 Selection for each Pair ----
  # Generate all possible pairs of factor levels
  level_pairs <- utils::combn(levels(clean_df$y), 2, simplify = FALSE)
  pair_labels <- sapply(level_pairs, paste, collapse = " vs. ")
  
  # Use lapply instead of a for loop for better performance and R style
  top_list <- lapply(seq_along(level_pairs), function(i) {
    
    current_pair <- level_pairs[[i]]
    
    # Identify indices of levels for the current pair
    priority_idx <- which(levels(clean_df$y) %in% current_pair)
    
    # Rank variables using the trident.arrange function
    ranking <- trident.arrange(
                  df          = numerics_filtered, 
                  y           = clean_df$y, 
                  by          = "hsd.p.value", 
                  gp.priority = priority_idx
               )
    
    # Return the names of the top 3 variables
    return(rownames(ranking)[1:3])
    
  })

  # Flatten the list of top variables
  all_top3_vars <- unlist(top_list)

  # 6. Final Export ----
  # Generate a global ranking for these specific variables
  global_ranking <- trident.arrange(df = numerics_filtered, y = clean_df$y)
  
  result <- list(
    top3var = all_top3_vars,
    ranked  = data.frame( group = rep(pair_labels, each = 3), 
                          global_ranking[all_top3_vars, , drop = FALSE]
                        )
  )

  return(result)
  
}
