# WARNING - Generated by {fusen} from dev/flat_utils-functions.Rmd: do not edit by hand # nolint: line_length_linter.

#' @title cleanNumerics
#' @description Removes rows or columns containing any NA values.
#' @param num A data frame or tibble.
#' @param margin Integer: 1 for rows, 2 for columns (default is 2).
#' @return A cleaned data frame.
#' @export
cleanNumerics <- function(num, margin = 2) {
  # Requirement: input must be a data frame
  req(is.data.frame(num))
  
  if (margin == 2) {
    # MARGIN 2: Select columns where ALL values are NOT NA
    return(dplyr::select(num, where(~ all(!is.na(.)))))
  } else if (margin == 1) {
    # MARGIN 1: Filter rows where ALL values are NOT NA
    # tidyr::drop_na() is the most efficient way to remove any row with at least one NA
    return(tidyr::drop_na(num))
  } else {
    stop("Invalid margin: use 1 for rows or 2 for columns.")
  }
}

#' Format with exponential form
#'
#' @title Format with exponential form
#' @description A character vector of JavaScript code to format numbers in exponential form.
#' @return string vector of JavaScript code
#' @export
exp_form <- function(){
   return( c("function(row, data) {",
             "for (i = 1; i < data.length; i++) {",
             "if (data[i] !== null && typeof data[i] == 'number') {",
             "$('td:eq(' + i + ')', row).html(data[i].toExponential(2));",
             "}",
             "}",
             "}"
            ) )
}

#' FactorFromFileName
#' @title FactorFromFileName
#' @description Extract a factor from a file name, based on a separator and a position. The extracted factor can be completed with a prefix and/or a suffix.
#' @param x A character vector of file names.
#' @param separator A character string used to split the file names.
#' @param position An integer indicating the position of the factor to extract after splitting the file names.
#' @param prefix Add a prefix to the factor
#' @param suffix Add a suffix to the factor
#' @importFrom stringr str_split
#' @return A character vector of extracted factors, optionally completed with a prefix and/or a suffix.
#' @export
#' 
#' @examples
#' # 1. We start with a character vector of file names
#' files <- c("2023_Albumin_01.csv", "2023_Hemoglobin_02.csv", "2023_Insulin_03.csv")
#'
#' # 2. We want to split by "_" and extract the second element (between the underscores)
#' #    We also want to add a prefix "ID_" to the extracted factor
#' names <- FactorFromFileName(
#'   x         = files, 
#'   separator = "_", 
#'   position  = 2, 
#'   prefix    = "ID_", 
#'   suffix    = ""
#' )
#'
#' print(names)
#' # Result : [1] "ID_Albumin" "ID_Hemoglobin" "ID_Insulin"
FactorFromFileName <- function(x, separator, position, prefix = "", suffix = "") {
  
  # 1. We split the string and directly retrieve the element at the chosen position
  extracted_values <- stringr::str_split_i(x, separator, position)
  
  # 2. We assemble with the prefix and suffix
  result <- paste0(prefix, extracted_values, suffix)
  
  return(result)
}

# getFactor
#' @title getFactor
#' @description Selects factor columns from a data frame and returns only the columns
#' specified by index.
#' @param df A data frame or tibble containing mixed column types.
#' @param idx Integer or numeric vector specifying which factor columns
#'        (after filtering) should be returned.
#' @return A data frame containing only the selected factor columns.
#' @export
getFactor  <- function(df, idx) dplyr::select_if(df, is.factor)[, idx]

# getNumeric
#' @title getNumeric
#' @description Selects and returns only the numeric columns from a data frame.
#' This is a convenience wrapper around `dplyr::select_if()` for
#' filtering numeric variables.
#' @param df A data frame or tibble containing mixed column types.
#' @return A data frame containing only the numeric columns of `df`.
#' @export
getNumeric <- function(df) dplyr::select_if(df, is.numeric)

# safeCompute
#' @title safeCompute
#' @description Evaluates an expression safely while handling errors gracefully.
#' If an error occurs, a modal dialog is displayed instead of stopping execution.
#' @param expr An expression to evaluate safely.
#' @param status A logical flag intended to track execution state (currently
#'        set internally and not reliably returned).
#' @return The result of `expr` if successful. In case of error, the function
#'         returns `NULL` invisibly after displaying a modal dialog.
#' @export
safeCompute <- function(expr, status) {
    status <- TRUE
    on.exit(status <- FALSE, add = TRUE)
    tryCatch(
        expr,
        error = function(e) {
            showModal(modalDialog(
                title = "Error detected",
                conditionMessage(e)
            ))
        }
    )
}

#' trident_program
#' @title trident_program
#' @description
#' Returns the file path to the Trident program executable bundled within the
#' package, depending on the operating system (Windows or Linux).
#' If the executable cannot be found via \code{system.file()}, a fallback path
#' within the package structure is used.
#' @return
#' A character string giving the path to the Trident executable file, and the
#' executable file.
#' @details
#' On Windows, the function looks for \code{prg.exe}, while on Linux it looks for
#' the \code{main} executable. The function first attempts to locate the file in
#' the installed package directory using \code{system.file()}, and falls back to
#' a relative path if needed.
#' @export
#' 
trident_program <- function() {

  OSSYSTEM  <- Sys.info()["sysname"]

   if (OSSYSTEM == "Windows"){

      PrgPath <- system.file("extdata", "structure", "prg", package = "trident")
      
      if (PrgPath == "") {
         PrgPath <- "inst/extdata/structure/prg/prg.exe"
      } else {
         PrgPath <- paste0(PrgPath, "/prg.exe")
      }

      run <- "prg.exe"

   } else if (OSSYSTEM == "Linux") {

      PrgPath <- system.file("extdata", "structure", "prg", package = "trident")
      
      if (PrgPath == "") {
         PrgPath <- "inst/extdata/structure/prg/main"
      } else {
         PrgPath <- paste0(PrgPath, "/main")
      }

      run <- "main"

   }

   return(c(PrgPath, run))
}

#' @title Utils functions
#' @description Internal grouping function
#' @noRd
utils <- function() {
  NULL
}
